# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Документация"
email: support@mrspro.ru
description: "Документация по продуктам компании «Мобильные решения для строительства»"
baseurl: "" #for versioning
url: "https://developers.mrspro.ru/"
color_theme:  "#f47f28"
color_text:  "#fff"
language:  "ru"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
